config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to:"todos#index"
  get "/completed/:id" ,to: "completed#update", as: "update_completed"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  after_update_commit {broadcast_replace_to "todos" }
  after_create_commit {broadcast_prepend_to "todos"}
  after_destroy_commit {broadcast_remove_to "todos"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/completed_controller.rb
class CompletedController < ApplicationController

  def update
    @todo = Todo.find(params[:id])
    @todo.completed = !@todo.completed
    @todo.save
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_helper.rb
module CompletedHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag dom_id(todo) do %>

  <div class="card">
    <div class="card-body <%= todo.completed ? "completed": "not-completed" %> ">
      <%= todo.title %> <br>
      <div class="btn-group float-right">
        <%= link_to "Complete",update_completed_path(id: todo.id, todo: todo),class:"btn btn-secondary" %>
        <%= button_to "Destroy",todo,method: :delete, class:"btn btn-danger" %>
      </div>
    </div>
  </div>

<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<h1>Hotwire Todo List</h1>

<%= turbo_stream_from "todos" %>

<%= turbo_frame_tag "todo_form" do %>
  <%= render "form" , todo: @todo %>
<% end %>

<%= turbo_frame_tag "todos" do %>
  <%= render @todos %>
<% end %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>